import React, { useState } from "react";
import { useSwipeable } from "react-swipeable";

// 🔹 Updated image array with src and descriptive alt text
const images = [
  {
    src: process.env.PUBLIC_URL + "/FoodImage1.jpg",
    alt: "Bowl With Egg Fruit and Lemon"
  },
  {
    src: process.env.PUBLIC_URL + "/FoodImage2.jpg",
    alt: "Overview of the Kitchen"
  },
  {
    src: process.env.PUBLIC_URL + "/FoodImage3.jpg",
    alt: "3 Bowls With Spaghetti On the Right"
  }
];

const FoodGallery = () => {
  const [index, setIndex] = useState(0);

  const swipeHandlers = useSwipeable({
    onSwipedLeft: () => setIndex((prev) => (prev + 1) % images.length),
    onSwipedRight: () => setIndex((prev) => (prev - 1 + images.length) % images.length),
    preventDefaultTouchmoveEvent: true,
    trackMouse: true
  });

  return (
    <div className="gallery-container" {...swipeHandlers}>
      <h2 style={{ textAlign: "center", color: "black", backgroundColor: "yellow", fontFamily: "RubikDirt" , fontWeight: "100" , marginBottom: "1rem" }}>
        All Photos On This Website Are Placeholder Images Generated by Razer Axon AI. They Will Be Replaced With Original Photos. Except the Mobile App Photo-That is My Original IP. Background Videos Are Stock, Public Domain from Clip Champ. 
      </h2>
      <img
        src={images[index].src}
        alt={images[index].alt}
        className="gallery-image"
      />
      <div className="gallery-controls">
        <button onClick={() => setIndex((prev) => (prev - 1 + images.length) % images.length)}>
          ⬅
        </button>
        <span>{index + 1} / {images.length}</span>
        <button onClick={() => setIndex((prev) => (prev + 1) % images.length)}>
          ➡
        </button>
      </div>
    </div>
  );
};

export default FoodGallery;
